---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg-deployment
spec:
  selector:
    matchLabels:
      app: msg # 选择这个指定标签执行
  replicas: 1 # 运行pod数量
  template:
    metadata:
      labels:
        app: msg # 标签
    spec:
      containers:
      - name: msg
        image: openim/msg:v2.1.0
        # imagePullPolicy: Always
        ports:
        - containerPort: 10130
        volumeMounts:
          - name: config
            mountPath: /Open-IM-Server/config
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: openim-config
  strategy: #更新策略
    type: RollingUpdate # 滚动更新