# The class cannot be named by Pascal or camel case.
# The class cannot be named by Pascal or camel case.
# If it is not used, the corresponding structure will not be set,
# and it will not be read naturally.
serverversion: 1.0.0
#---------------Infrastructure configuration---------------------#

mysql:
  dbMysqlAddress: [ 127.0.0.1:13306 ] #mysql地址 目前仅支持单机，默认即可
  dbMysqlUserName: root #mysql用户名，建议修改
  dbMysqlPassword: openIM # mysql密码，建议修改
  dbMysqlDatabaseName: freechat #默认即可
  dbTableName: eMsg #默认即可
  dbMsgTableNum: 1
  dbMaxOpenConns: 20
  dbMaxIdleConns: 10
  dbMaxLifeTime: 120

mongo:
  dbUri: ""#当dbUri值不为空则直接使用该值
  dbAddress: 127.0.0.1:37017  #单机时为mongo地址，使用分片集群时，为mongos地址 默认即可
  dbDirect: false
  dbTimeout: 60
  dbDatabase: openIM  #mongo db 默认即可
  dbSource: admin
  dbUserName:  #mongo用户名，建议先不设置
  dbPassword:  #mongo密码，建议先不设置
  dbMaxPoolSize: 100
  dbRetainChatRecords: 3650 #mongo保存离线消息时间（天），根据需求修改

redis:
  dbAddress: [ 127.0.0.1:16379 ] #redis地址 单机时，填写一个地址即可，使用redis集群时候，填写集群中多个节点地址（主从地址都可以填写，增加容灾能力），默认即可
  dbMaxIdle: 128
  dbMaxActive: 0
  dbIdleTimeout: 120
  dbPassWord: openIM #redis密码 建议修改
  enableCluster: false #如果外部redis以集群方式启动，需要打开此开关

api:
  openImApiPort: [ 10002 ] #api服务端口，默认即可，需要开放此端口或做nginx转发
  listenIP: 0.0.0.0
cmsapi:
  openImCmsApiPort: [ 10006 ] #管理后台api服务端口，默认即可，需要开放此端口或做nginx转发
  listenIP: 0.0.0.0

  #---------------freechat_api configuration---------------------#
  #The following configuration items are applied to freechat_api configuration
freechat:
  listenIP: 0.0.0.0
  #freechat对外服务端口，默认即可，需要开放此端口或做nginx转发
  freechatPort: [ 10005 ]
  testDepartMentID: 001
  imAPIURL: http://127.0.0.1:10002

rtc:
  signalTimeout: 35